;;; Executable integer-only Asteroids. The seed has no trigonometry, so the
;;; displayed source deliberately declares four cardinal ship headings.
;;; State: (ship-x ship-y heading score bullets asteroids)

(defn app.at (xs n) (if (= n 0) (car xs) (app.at (cdr xs) (- n 1))))
(defn app.input? (input name) (let ((row (assoc name input))) (if row (= (app.at row 1) 1) false)))
(defn app.wrap (n limit) (if (< n 0) (+ n limit) (if (>= n limit) (- n limit) n)))
(defn app.dx (h) (cond ((= h 0) 1) ((= h 2) -1) (true 0)))
(defn app.dy (h) (cond ((= h 1) 1) ((= h 3) -1) (true 0)))
(defn app.remove-at (xs n) (if (= n 0) (cdr xs) (cons (car xs) (app.remove-at (cdr xs) (- n 1)))))

(defn app.mount ()
  '(mount 640 360 Asteroids ((left hold rotate-left (ArrowLeft a))
    (right hold rotate-right (ArrowRight d)) (thrust hold thrust (ArrowUp w))
    (fire press fire (Space)))))
(defn app.initial-state () (list 320 180 3 0 nil '((80 70 8 6 24) (530 85 -7 8 29) (120 290 9 -5 20) (520 290 -8 -6 23))))
(defn app.heading (h input) (if (app.input? input 'left) (if (= h 0) 3 (- h 1)) (if (app.input? input 'right) (if (= h 3) 0 (+ h 1)) h)))
(defn app.move-rock (r) (list (app.wrap (+ (app.at r 0) (app.at r 2)) 640) (app.wrap (+ (app.at r 1) (app.at r 3)) 360) (app.at r 2) (app.at r 3) (app.at r 4)))
(defn app.move-bullet (b) (list (app.wrap (+ (app.at b 0) (app.at b 2)) 640) (app.wrap (+ (app.at b 1) (app.at b 3)) 360) (app.at b 2) (app.at b 3) (- (app.at b 4) 1)))
(defn app.hit (b rocks n)
  (if (nil? rocks) -1 (let ((r (car rocks)))
    (if (and (<= (- (app.at b 0) (app.at r 0)) (app.at r 4)) (>= (- (app.at b 0) (app.at r 0)) (- 0 (app.at r 4)))
             (<= (- (app.at b 1) (app.at r 1)) (app.at r 4)) (>= (- (app.at b 1) (app.at r 1)) (- 0 (app.at r 4)))) n
        (app.hit b (cdr rocks) (+ n 1))))))
(defn app.resolve (bullets rocks score)
  (if (nil? bullets) (list nil rocks score)
    (let ((b (app.move-bullet (car bullets))) (rest (app.resolve (cdr bullets) rocks score)))
      (let ((hit (if (<= (app.at b 4) 0) -1 (app.hit b (app.at rest 1) 0))))
        (if (>= hit 0) (list (app.at rest 0) (app.remove-at (app.at rest 1) hit) (+ (app.at rest 2) 100))
            (if (<= (app.at b 4) 0) rest (list (cons b (app.at rest 0)) (app.at rest 1) (app.at rest 2))))))))
(defn app.fire (bullets x y h)
  (if (>= (length bullets) 5) bullets (cons (list (app.wrap (+ x (* (app.dx h) 16)) 640) (app.wrap (+ y (* (app.dy h) 16)) 360) (* (app.dx h) 40) (* (app.dy h) 40) 10) bullets)))
(defn app.step (state input)
  (let ((x (app.at state 0)) (y (app.at state 1)) (h (app.heading (app.at state 2) input)) (score (app.at state 3)) (bullets (app.at state 4)) (rocks (app.at state 5)))
    (let ((next-bullets (if (app.input? input 'fire) (app.fire bullets x y h) bullets)))
      (let ((resolved (app.resolve next-bullets (map app.move-rock rocks) score)))
        (list (app.wrap (+ x (if (app.input? input 'thrust) (* (app.dx h) 10) 0)) 640) (app.wrap (+ y (if (app.input? input 'thrust) (* (app.dy h) 10) 0)) 360) h (app.at resolved 2) (app.at resolved 0) (app.at resolved 1))))))
(defn app.rocks (rocks) (if (nil? rocks) nil (cons (list 'circle (app.at (car rocks) 0) (app.at (car rocks) 1) (app.at (car rocks) 4) 4) (app.rocks (cdr rocks)))))
(defn app.bullets (bullets) (if (nil? bullets) nil (cons (list 'circle (app.at (car bullets) 0) (app.at (car bullets) 1) 3 2) (app.bullets (cdr bullets)))))
(defn app.ship (x y h)
  (if (= h 0) (list (list 'line x y (+ x 18) y 1 2) (list 'line x (- y 10) (+ x 18) y 1 2) (list 'line x (+ y 10) (+ x 18) y 1 2))
    (if (= h 1) (list (list 'line x y x (+ y 18) 1 2) (list 'line (- x 10) y x (+ y 18) 1 2) (list 'line (+ x 10) y x (+ y 18) 1 2))
      (if (= h 2) (list (list 'line x y (- x 18) y 1 2) (list 'line x (- y 10) (- x 18) y 1 2) (list 'line x (+ y 10) (- x 18) y 1 2))
        (list (list 'line x y x (- y 18) 1 2) (list 'line (- x 10) y x (- y 18) 1 2) (list 'line (+ x 10) y x (- y 18) 1 2))))))
(defn app.view (s) (list (cons 'draw (append (list (list 'clear 0)) (append (app.ship (app.at s 0) (app.at s 1) (app.at s 2)) (append (app.rocks (app.at s 5)) (app.bullets (app.at s 4)))))) (list 'status (app.at s 3) (length (app.at s 5)))))
(defn app.frame (s input) (let ((next (app.step s input))) (cons (list 'state next) (app.view next))))
