;;; WL_MAIN.C - SaveTheGame / LoadTheGame, ported to YALisp.
;;;
;;; The source streams DOS structs to a file handle. The current stage-05 file
;;; API is contract-only, so this translation returns/accepts one Lisp-owned byte
;;; buffer. Gamestate keeps the original 68-byte instrumented layout. Pointer-
;;; linked objtype records become the port's complete structure-of-arrays actor
;;; storage; all currently-owned live player, map, area, actor, static, door, and
;;; pushwall state is round-tripped. The source checksum algorithm and its
;;; corrupt-save penalty are preserved.

(define wl.SAVE-GAMESTATE 0)
(define wl.SAVE-LEVELRATIOS 68)
(define wl.SAVE-TILEMAP 148)
(define wl.SAVE-ACTORAT-WALL 4244)
(define wl.SAVE-AREACONNECT 8340)
(define wl.SAVE-AREABYPLAYER 9709)
(define wl.SAVE-PLAYER 9746)
(define wl.SAVE-ACTORCOUNT 9778)
(define wl.SAVE-ACTORX 9780)
(define wl.SAVE-ACTORY 10380)
(define wl.SAVE-ACTORDISTANCE 10980)
(define wl.SAVE-ACTORTILEX 11580)
(define wl.SAVE-ACTORTILEY 11730)
(define wl.SAVE-ACTORDIR 11880)
(define wl.SAVE-ACTORCLASS 12030)
(define wl.SAVE-ACTORACTIVE 12180)
(define wl.SAVE-ACTORPHASE 12330)
(define wl.SAVE-ACTORFLAGS 12480)
(define wl.SAVE-ACTORAREA 12630)
(define wl.SAVE-ACTORTICCOUNT 12780)
(define wl.SAVE-ACTORSPEED 13080)
(define wl.SAVE-ACTORHITPOINTS 13380)
(define wl.SAVE-ACTORTEMP2 13680)
(define wl.SAVE-ACTORAUX 13980)
(define wl.SAVE-ACTORVIEWX 14880)
(define wl.SAVE-ACTORTRANSX 15480)
(define wl.SAVE-ACTORVIEWHEIGHT 16080)
(define wl.SAVE-ACTORAT 16380)
(define wl.SAVE-STATICCOUNT 20476)
(define wl.SAVE-STATICX 20478)
(define wl.SAVE-STATICY 20878)
(define wl.SAVE-STATICSHAPENUM 21278)
(define wl.SAVE-STATICFLAGS 22078)
(define wl.SAVE-STATICITEM 22478)
(define wl.SAVE-DOORNUM 22878)
(define wl.SAVE-DOORPOSITION 22880)
(define wl.SAVE-DOORTILEX 23008)
(define wl.SAVE-DOORTILEY 23072)
(define wl.SAVE-DOORVERTICAL 23136)
(define wl.SAVE-DOORLOCK 23200)
(define wl.SAVE-DOORACTION 23264)
(define wl.SAVE-DOORTICCOUNT 23328)
(define wl.SAVE-PWALL 23456)
(define wl.SAVE-CHECKSUM 23466)
(define wl.SAVE-BYTES 23470)

(define wl.killx 0)
(define wl.killy 0)
(define wl.victoryflag 0)

(defn wl.save-i16! (save at value)
  (u16! save at (if (< value 0) (+ value 65536) value)))

(defn wl.write-gamestate (save)
  (begin
    (wl.save-i16! save 0 wl.difficulty)
    (wl.save-i16! save 2 wl.map)
    (u32! save 4 wl.oldscore)
    (u32! save 8 wl.score)
    (u32! save 12 wl.nextextra)
    (wl.save-i16! save 16 wl.lives)
    (wl.save-i16! save 18 wl.health)
    (wl.save-i16! save 20 wl.ammo)
    (wl.save-i16! save 22 wl.keys)
    (wl.save-i16! save 24 wl.bestweapon)
    (wl.save-i16! save 26 wl.weapon)
    (wl.save-i16! save 28 wl.chosenweapon)
    (wl.save-i16! save 30 wl.faceframe)
    (wl.save-i16! save 32 wl.attackframe)
    (wl.save-i16! save 34 wl.attackcount)
    (wl.save-i16! save 36 wl.weaponframe)
    (wl.save-i16! save 38 wl.episode)
    (wl.save-i16! save 40 wl.secretcount)
    (wl.save-i16! save 42 wl.treasurecount)
    (wl.save-i16! save 44 wl.killcount)
    (wl.save-i16! save 46 wl.secrettotal)
    (wl.save-i16! save 48 wl.treasuretotal)
    (wl.save-i16! save 50 wl.killtotal)
    (u32! save 52 app.time-count)
    (u32! save 56 wl.killx)
    (u32! save 60 wl.killy)
    (wl.save-i16! save 64 wl.victoryflag)
    (u16! save 66 0)))

(defn wl.read-gamestate (save)
  (begin
    (set! wl.difficulty (i16@ save 0))
    (set! wl.map (i16@ save 2))
    (set! wl.oldscore (i32@ save 4))
    (set! wl.score (i32@ save 8))
    (set! wl.nextextra (i32@ save 12))
    (set! wl.lives (i16@ save 16))
    (set! wl.health (i16@ save 18))
    (set! wl.ammo (i16@ save 20))
    (set! wl.keys (i16@ save 22))
    (set! wl.bestweapon (i16@ save 24))
    (set! wl.weapon (i16@ save 26))
    (set! wl.chosenweapon (i16@ save 28))
    (set! wl.faceframe (i16@ save 30))
    (set! wl.attackframe (i16@ save 32))
    (set! wl.attackcount (i16@ save 34))
    (set! wl.weaponframe (i16@ save 36))
    (set! wl.episode (i16@ save 38))
    (set! wl.secretcount (i16@ save 40))
    (set! wl.treasurecount (i16@ save 42))
    (set! wl.killcount (i16@ save 44))
    (set! wl.secrettotal (i16@ save 46))
    (set! wl.treasuretotal (i16@ save 48))
    (set! wl.killtotal (i16@ save 50))
    (set! app.time-count (i32@ save 52))
    (set! wl.killx (i32@ save 56))
    (set! wl.killy (i32@ save 60))
    (set! wl.victoryflag (i16@ save 64))))

(defn wl.copy-save! (save at source count)
  (bytes.copy save at source 0 count))

(defn wl.copy-load! (target save at count)
  (bytes.copy target 0 save at count))

;;; Non-SPEAR saves persist eight ten-byte LRstruct rows immediately after
;;; gamestate. The fifth element in the port's transient completion result is
;;; the just-awarded bonus, not part of the source LevelRatios structure.
(defn wl.write-level-ratios (save index)
  (if (= index 8)
      save
      (let ((ratio (wl.ratio-or-zero index))
            (at (+ wl.SAVE-LEVELRATIOS (* index 10))))
        (begin
          (wl.save-i16! save at (wl.play-at ratio 0))
          (wl.save-i16! save (+ at 2) (wl.play-at ratio 1))
          (wl.save-i16! save (+ at 4) (wl.play-at ratio 2))
          (u32! save (+ at 6) (wl.play-at ratio 3))
          (wl.write-level-ratios save (+ index 1))))))

(defn wl.read-level-ratios (save index ratios)
  (if (= index 8)
      ratios
      (let ((at (+ wl.SAVE-LEVELRATIOS (* index 10))))
        (wl.read-level-ratios save (+ index 1)
          (append ratios
            (list (list (i16@ save at) (i16@ save (+ at 2))
                        (i16@ save (+ at 4)) (i32@ save (+ at 6)))))))))

(defn wl.write-owned-state (save)
  (begin
    (wl.write-gamestate save)
    (wl.write-level-ratios save 0)
    (wl.copy-save! save wl.SAVE-TILEMAP wl.tilemap 4096)
    (wl.copy-save! save wl.SAVE-ACTORAT-WALL wl.actorat-wall 4096)
    (wl.copy-save! save wl.SAVE-AREACONNECT wl.areaconnect 1369)
    (wl.copy-save! save wl.SAVE-AREABYPLAYER wl.areabyplayer 37)
    (wl.copy-save! save wl.SAVE-PLAYER wl.player 32)
    (u16! save wl.SAVE-ACTORCOUNT wl.actorcount)
    (wl.copy-save! save wl.SAVE-ACTORX wl.actorx 600)
    (wl.copy-save! save wl.SAVE-ACTORY wl.actory 600)
    (wl.copy-save! save wl.SAVE-ACTORDISTANCE wl.actordistance 600)
    (wl.copy-save! save wl.SAVE-ACTORTILEX wl.actortilex 150)
    (wl.copy-save! save wl.SAVE-ACTORTILEY wl.actortiley 150)
    (wl.copy-save! save wl.SAVE-ACTORDIR wl.actordir 150)
    (wl.copy-save! save wl.SAVE-ACTORCLASS wl.actorclass 150)
    (wl.copy-save! save wl.SAVE-ACTORACTIVE wl.actoractive 150)
    (wl.copy-save! save wl.SAVE-ACTORPHASE wl.actorphase 150)
    (wl.copy-save! save wl.SAVE-ACTORFLAGS wl.actorflags 150)
    (wl.copy-save! save wl.SAVE-ACTORAREA wl.actorarea 150)
    (wl.copy-save! save wl.SAVE-ACTORTICCOUNT wl.actorticcount 300)
    (wl.copy-save! save wl.SAVE-ACTORSPEED wl.actorspeed 300)
    (wl.copy-save! save wl.SAVE-ACTORHITPOINTS wl.actorhitpoints 300)
    (wl.copy-save! save wl.SAVE-ACTORTEMP2 wl.actortemp2 300)
    (wl.copy-save! save wl.SAVE-ACTORAUX wl.actoraux 900)
    (wl.copy-save! save wl.SAVE-ACTORVIEWX wl.actorviewx 600)
    (wl.copy-save! save wl.SAVE-ACTORTRANSX wl.actortransx 600)
    (wl.copy-save! save wl.SAVE-ACTORVIEWHEIGHT wl.actorviewheight 300)
    (wl.copy-save! save wl.SAVE-ACTORAT wl.actorat 4096)
    (u16! save wl.SAVE-STATICCOUNT wl.staticcount)
    (wl.copy-save! save wl.SAVE-STATICX wl.staticx 400)
    (wl.copy-save! save wl.SAVE-STATICY wl.staticy 400)
    (wl.copy-save! save wl.SAVE-STATICSHAPENUM wl.staticshapenum 800)
    (wl.copy-save! save wl.SAVE-STATICFLAGS wl.staticflags 400)
    (wl.copy-save! save wl.SAVE-STATICITEM wl.staticitem 400)
    (u16! save wl.SAVE-DOORNUM wl.doornum)
    (wl.copy-save! save wl.SAVE-DOORPOSITION wl.doorposition 128)
    (wl.copy-save! save wl.SAVE-DOORTILEX wl.doortilex 64)
    (wl.copy-save! save wl.SAVE-DOORTILEY wl.doortiley 64)
    (wl.copy-save! save wl.SAVE-DOORVERTICAL wl.doorvertical 64)
    (wl.copy-save! save wl.SAVE-DOORLOCK wl.doorlock 64)
    (wl.copy-save! save wl.SAVE-DOORACTION wl.dooraction 64)
    (wl.copy-save! save wl.SAVE-DOORTICCOUNT wl.doorticcount 128)
    (wl.save-i16! save wl.SAVE-PWALL wl.pwallstate)
    (wl.save-i16! save (+ wl.SAVE-PWALL 2) wl.pwallx)
    (wl.save-i16! save (+ wl.SAVE-PWALL 4) wl.pwally)
    (wl.save-i16! save (+ wl.SAVE-PWALL 6) wl.pwalldir)
    (wl.save-i16! save (+ wl.SAVE-PWALL 8) wl.pwallpos)))

(defn wl.read-owned-state (save)
  (begin
    (wl.read-gamestate save)
    (set! wl.level-ratios (wl.read-level-ratios save 0 nil))
    (wl.copy-load! wl.tilemap save wl.SAVE-TILEMAP 4096)
    (wl.copy-load! wl.actorat-wall save wl.SAVE-ACTORAT-WALL 4096)
    (wl.copy-load! wl.areaconnect save wl.SAVE-AREACONNECT 1369)
    (wl.copy-load! wl.areabyplayer save wl.SAVE-AREABYPLAYER 37)
    (wl.copy-load! wl.player save wl.SAVE-PLAYER 32)
    (set! wl.actorcount (u16@ save wl.SAVE-ACTORCOUNT))
    (wl.copy-load! wl.actorx save wl.SAVE-ACTORX 600)
    (wl.copy-load! wl.actory save wl.SAVE-ACTORY 600)
    (wl.copy-load! wl.actordistance save wl.SAVE-ACTORDISTANCE 600)
    (wl.copy-load! wl.actortilex save wl.SAVE-ACTORTILEX 150)
    (wl.copy-load! wl.actortiley save wl.SAVE-ACTORTILEY 150)
    (wl.copy-load! wl.actordir save wl.SAVE-ACTORDIR 150)
    (wl.copy-load! wl.actorclass save wl.SAVE-ACTORCLASS 150)
    (wl.copy-load! wl.actoractive save wl.SAVE-ACTORACTIVE 150)
    (wl.copy-load! wl.actorphase save wl.SAVE-ACTORPHASE 150)
    (wl.copy-load! wl.actorflags save wl.SAVE-ACTORFLAGS 150)
    (wl.copy-load! wl.actorarea save wl.SAVE-ACTORAREA 150)
    (wl.copy-load! wl.actorticcount save wl.SAVE-ACTORTICCOUNT 300)
    (wl.copy-load! wl.actorspeed save wl.SAVE-ACTORSPEED 300)
    (wl.copy-load! wl.actorhitpoints save wl.SAVE-ACTORHITPOINTS 300)
    (wl.copy-load! wl.actortemp2 save wl.SAVE-ACTORTEMP2 300)
    (wl.copy-load! wl.actoraux save wl.SAVE-ACTORAUX 900)
    (wl.copy-load! wl.actorviewx save wl.SAVE-ACTORVIEWX 600)
    (wl.copy-load! wl.actortransx save wl.SAVE-ACTORTRANSX 600)
    (wl.copy-load! wl.actorviewheight save wl.SAVE-ACTORVIEWHEIGHT 300)
    (wl.copy-load! wl.actorat save wl.SAVE-ACTORAT 4096)
    (set! wl.staticcount (u16@ save wl.SAVE-STATICCOUNT))
    (wl.copy-load! wl.staticx save wl.SAVE-STATICX 400)
    (wl.copy-load! wl.staticy save wl.SAVE-STATICY 400)
    (wl.copy-load! wl.staticshapenum save wl.SAVE-STATICSHAPENUM 800)
    (wl.copy-load! wl.staticflags save wl.SAVE-STATICFLAGS 400)
    (wl.copy-load! wl.staticitem save wl.SAVE-STATICITEM 400)
    (set! wl.doornum (u16@ save wl.SAVE-DOORNUM))
    (wl.copy-load! wl.doorposition save wl.SAVE-DOORPOSITION 128)
    (wl.copy-load! wl.doortilex save wl.SAVE-DOORTILEX 64)
    (wl.copy-load! wl.doortiley save wl.SAVE-DOORTILEY 64)
    (wl.copy-load! wl.doorvertical save wl.SAVE-DOORVERTICAL 64)
    (wl.copy-load! wl.doorlock save wl.SAVE-DOORLOCK 64)
    (wl.copy-load! wl.dooraction save wl.SAVE-DOORACTION 64)
    (wl.copy-load! wl.doorticcount save wl.SAVE-DOORTICCOUNT 128)
    (set! wl.pwallstate (i16@ save wl.SAVE-PWALL))
    (set! wl.pwallx (i16@ save (+ wl.SAVE-PWALL 2)))
    (set! wl.pwally (i16@ save (+ wl.SAVE-PWALL 4)))
    (set! wl.pwalldir (i16@ save (+ wl.SAVE-PWALL 6)))
    (set! wl.pwallpos (i16@ save (+ wl.SAVE-PWALL 8)))))

(defn wl.do-checksum (source at size checksum)
  (if (<= size 1)
      checksum
      (wl.do-checksum source (+ at 1) (- size 1)
                      (+ checksum (bit.xor (u8@ source at)
                                           (u8@ source (+ at 1)))))))

(defn wl.save-checksum (save)
  (let ((a (wl.do-checksum save wl.SAVE-GAMESTATE 68 0)))
    (let ((b (wl.do-checksum save wl.SAVE-LEVELRATIOS 80 a)))
      (let ((c (wl.do-checksum save wl.SAVE-TILEMAP 4096 b)))
        (let ((d (wl.do-checksum save wl.SAVE-ACTORAT-WALL 4096 c)))
          (let ((e (wl.do-checksum save wl.SAVE-ACTORAT 4096 d)))
            (let ((f (wl.do-checksum save wl.SAVE-STATICCOUNT 2402 e)))
              (let ((g (wl.do-checksum save wl.SAVE-DOORNUM 578 f)))
                (wl.do-checksum save wl.SAVE-PWALL 10 g)))))))))

(defn wl.save-the-game ()
  (let ((save (bytes.alloc wl.SAVE-BYTES)))
    (begin
      (wl.write-owned-state save)
      (u32! save wl.SAVE-CHECKSUM (wl.save-checksum save))
      save)))

(defn wl.load-the-game (save)
  (if (or (nil? save) (not (= (bytes.length save) wl.SAVE-BYTES)))
      false
      (let ((checksum (wl.save-checksum save)))
        (let ((oldchecksum (u32@ save wl.SAVE-CHECKSUM)))
          (begin
            (wl.read-owned-state save)
            (set! wl.loadedgame 1)
            (if (= oldchecksum checksum)
                true
                (begin
                  ;; Preserve the original anti-cheat recovery values.
                  (set! wl.score 0)
                  (set! wl.lives 1)
                  (set! wl.weapon wl.WP-PISTOL)
                  (set! wl.chosenweapon wl.WP-PISTOL)
                  (set! wl.bestweapon wl.WP-PISTOL)
                  (set! wl.ammo 8)
                  false)))))))
