;;; Applications documentation is rendered by the bounded DOM Lisp runtime.
(define el (lambda args args))
(defn at (key value) (list key value))
(defn cls (value) (at 'class value))
(defn href (value) (at 'href value))
(defn id (value) (at 'id value))
(defn click (event) (at 'on-click event))
(defn aria (key value) (at key value))
(defn link (path label) (el 'a (list (href path)) label))
(defn nav-link (path label) (el 'li nil (el 'a (list (cls 'project-nav-link) (href path)) label)))
(defn stage-link (number path label active)
  (el 'li nil (el 'a (if active
    (list (cls "project-nav-link active") (href path) (aria 'aria-current "page"))
    (list (cls 'project-nav-link) (href path))) number " " label)))
(defn map-link (number path title note)
  (el 'a (list (href path)) (el 'span nil number) (el 'strong nil title) (el 'small nil note)))
(defn menu-state (state) (car state))
(defn theme-state (state) (car (cdr state)))
(defn shell-class (state) (if (eq? (menu-state state) 'open) "docs-shell nav-open sidebar-collapsed" 'docs-shell))
(defn menu-aria (state) (if (eq? (menu-state state) 'open) "true" "false"))
(defn theme-name (state) (if (eq? (theme-state state) 'dark) 'dark 'light))
(defn theme-label (state) (if (eq? (theme-state state) 'dark) "Light" "Dark"))
(defn theme-icon (state) (if (eq? (theme-state state) 'dark) "☀" "◐"))
(defn docs-navigation ()
  (el 'div (list (cls 'project-navigation))
    (el 'p (list (cls 'project-nav-label)) "Project navigation")
    (el 'nav (list (cls 'project-nav) (aria 'aria-label "Project navigation"))
      (el 'ul (list (cls 'project-nav-tree))
        (nav-link '/ "Project overview")
        (nav-link '/docs/ "Documentation overview")
        (el 'li nil
          (el 'a (list (cls 'project-nav-link) (href '/docs/foundation/) (aria 'aria-expanded "true")) "Foundation overview")
          (el 'ul (list (cls 'project-nav-children))
            (stage-link "01" '/docs/seed/ "Seed" false)
            (stage-link "02" '/docs/bootstrap/ "Bootstrap" false)
            (stage-link "03" '/docs/compiler/ "Compiler" false)
            (stage-link "04" "/docs/applications/" "Applications" true)))
        (nav-link '/docs/dom/ "05 Interfaces")
        (nav-link '/repl/ "REPL")
        (nav-link '/examples/ "Examples")))))
(defn app.initial-state () '(closed dark))
(defn app.event (state event)
  (if (eq? event 'toggle-menu)
    (list (if (eq? (menu-state state) 'open) 'closed 'open) (theme-state state))
    (if (eq? event 'toggle-theme)
      (list (menu-state state) (if (eq? (theme-state state) 'dark) 'light 'dark))
      state)))
(defn app.view (state)
  (el 'fragment (list (at 'document-theme (theme-name state)))
    (el 'a (list (cls 'skip-link) (href '#content)) "Skip to content")
    (el 'header (list (cls 'docs-header))
      (el 'a (list (cls 'brand) (href '/) (aria 'aria-label "YALisp home")) "Y" (el 'span nil "A") "LISP")
      (el 'div (list (cls 'header-actions))
        (el 'button (list (cls 'theme-toggle) (at 'type 'button) (click 'toggle-theme)) (theme-icon state) (theme-label state))
        (el 'button (list (cls 'docs-menu) (at 'type 'button) (click 'toggle-menu) (aria 'aria-label "Toggle documentation navigation") (aria 'aria-expanded (menu-aria state))) (el 'span nil) (el 'span nil))))
    (el 'div (list (cls (shell-class state)))
      (el 'aside (list (cls 'docs-nav) (aria 'aria-label "Project navigation") (at 'data-project-navigation 'true)) nil)
      (el 'main (list (id 'content))
        (el 'p (list (cls 'eyebrow)) "Foundation / Applications")
        (el 'section nil
          (el 'p (list (cls 'section-number)) "Applications")
          (el 'h1 nil "Build practical tools" (el 'br nil) (el 'em nil "from the language."))
          (el 'p (list (cls 'lede)) "Applications use YALisp's interfaces for low-level computation, portable system services, and document-and-event interaction.")
          (el 'div (list (cls 'interface-map) (aria 'aria-label "YALisp application interfaces"))
            (map-link "01" "/docs/assembly/" "Assembly" "Low-level WebAssembly computation")
            (map-link "02" "/docs/system-interface/" "System interface" "Portable access to host services")
            (map-link "03" "/docs/dom/" "DOM" "Portable documents and events"))
          (el 'p (list (cls 'interface-note)) "The intended application bootstrap is a proposed DOM-level helper that creates one root surface, wires lifecycle and input, and selects the platform binding. Browser builds would use the native DOM; SDL and bare-metal builds would initialize YALisp's lightweight SDL-backed document tree and surface. Its name, signature, ownership rules, and additional-root behavior remain to be defined, and no such helper is implemented yet.")
          (el 'p (list (cls 'interface-note)) "The " (link "/examples/" "Examples gallery") " makes that boundary concrete: Hello World runs through the current seed with its complete browser and CLI hosts shown, while Pong, Breakout, and Asteroids execute their complete displayed YALISP sources through the generic Canvas browser binding. None of the games claim an implemented native YALISP DOM, SDL, or Game Runtime binding."))))))
