;;; Assembly inventory view: assembly-inventory is supplied as checked-in Lisp data.
(define el (lambda args args))
(defn at (key value) (list key value))
(defn cls (value) (at 'class value))
(defn href (value) (at 'href value))
(defn id (value) (at 'id value))
(defn click (event) (at 'on-click event))
(defn aria (key value) (at key value))
(defn link (path label) (el 'a (list (href path)) label))
(defn nav-link (path label active)
  (el 'li nil (el 'a (if active (list (cls "project-nav-link active") (href path) (aria 'aria-current "page")) (list (cls 'project-nav-link) (href path))) label)))
(defn menu-state (state) (car state))
(defn theme-state (state) (car (cdr state)))
(defn shell-class (state) (if (eq? (menu-state state) 'open) "docs-shell nav-open sidebar-collapsed" 'docs-shell))
(defn menu-aria (state) (if (eq? (menu-state state) 'open) "true" "false"))
(defn theme-name (state) (if (eq? (theme-state state) 'dark) 'dark 'light))
(defn theme-label (state) (if (eq? (theme-state state) 'dark) "Light" "Dark"))
(defn theme-icon (state) (if (eq? (theme-state state) 'dark) "☀" "◐"))
(defn function-card (name)
  (el 'li nil (el 'code nil name) (el 'span nil "Candidate WebAssembly instruction in the Assembly interface.")))
(defn inventory-group (entry)
  (let ((title (car entry)) (functions (car (cdr entry))))
    (el 'details nil (el 'summary nil title " (" (to-string (length functions)) ")") (el 'ul (list (cls 'function-reference)) (map function-card functions)))))
(defn docs-navigation ()
  (el 'div (list (cls 'project-navigation))
    (el 'p (list (cls 'project-nav-label)) "Project navigation")
    (el 'nav (list (cls 'project-nav) (aria 'aria-label "Project navigation"))
      (el 'ul (list (cls 'project-nav-tree))
        (nav-link '/ "Project overview" false)
        (nav-link '/docs/ "Documentation overview" false)
        (nav-link '/docs/foundation/ "Foundation overview" false)
        (nav-link "/docs/assembly/" "05.01 Assembly" true)
        (nav-link '/docs/system-interface/ "05.02 System interface" false)
        (nav-link '/docs/dom/ "05.03 DOM" false)
        (nav-link '/docs/sdl/ "05.04 SDL" false)
        (nav-link '/repl/ "REPL" false)
        (nav-link '/examples/ "Examples" false)))))
(defn app.initial-state () '(closed dark))
(defn app.event (state event)
  (if (eq? event 'toggle-menu) (list (if (eq? (menu-state state) 'open) 'closed 'open) (theme-state state))
    (if (eq? event 'toggle-theme) (list (menu-state state) (if (eq? (theme-state state) 'dark) 'light 'dark)) state)))
(defn app.view (state)
  (el 'fragment (list (at 'document-theme (theme-name state)))
    (el 'a (list (cls 'skip-link) (href '#content)) "Skip to content")
    (el 'header (list (cls 'docs-header))
      (el 'a (list (cls 'brand) (href '/) (aria 'aria-label "YALisp home")) "Y" (el 'span nil "A") "LISP")
      (el 'div (list (cls 'header-actions))
        (el 'button (list (cls 'theme-toggle) (at 'type 'button) (click 'toggle-theme)) (theme-icon state) (theme-label state))
        (el 'button (list (cls 'docs-menu) (at 'type 'button) (click 'toggle-menu) (aria 'aria-label "Toggle documentation navigation") (aria 'aria-expanded (menu-aria state))) (el 'span nil) (el 'span nil))))
    (el 'div (list (cls (shell-class state)))
      (el 'aside (list (cls 'docs-nav) (aria 'aria-label "Project navigation") (at 'data-project-navigation 'true)) nil)
      (el 'main (list (id 'content))
        (el 'p (list (cls 'eyebrow)) "Interfaces / 01")
        (el 'section (list (id 'assembly))
          (el 'p (list (cls 'section-number)) "Assembly")
          (el 'h1 nil "WebAssembly," (el 'br nil) (el 'em nil "named for Lisp."))
          (el 'p (list (cls 'lede)) "Every Assembly function is presented in its underlying WebAssembly instruction family. The public YALisp contract will adopt entries from this inventory deliberately.")
          (el 'div (list (cls 'inventory)) (map inventory-group assembly-inventory))
          (el 'p (list (cls 'interface-note)) "This is the normative YALisp Assembly contract. The inventory is researched from the predecessor interface; inclusion records the candidate surface while YALisp decides what becomes supported."))))))
