;;; Bootstrap documentation; documented-source is the exact checked-in boot.lisp.
(define el (lambda args args))
(defn at (key value) (list key value))
(defn cls (value) (at 'class value))
(defn href (value) (at 'href value))
(defn id (value) (at 'id value))
(defn click (event) (at 'on-click event))
(defn aria (key value) (at key value))
(defn link (path label) (el 'a (list (href path)) label))
(defn nav-link (path label) (el 'li nil (el 'a (list (cls 'project-nav-link) (href path)) label)))
(defn stage-link (number path label active)
  (el 'li nil (el 'a (if active
    (list (cls "project-nav-link active") (href path) (aria 'aria-current "page") (at 'data-nav 'stage))
    (list (cls 'project-nav-link) (href path) (at 'data-nav 'stage))) number " " label)))
(defn menu-state (state) (car state))
(defn theme-state (state) (car (cdr state)))
(defn shell-class (state) (if (eq? (menu-state state) 'open) "docs-shell nav-open" 'docs-shell))
(defn menu-aria (state) (if (eq? (menu-state state) 'open) "true" "false"))
(defn theme-name (state) (if (eq? (theme-state state) 'dark) 'dark 'light))
(defn theme-label (state) (if (eq? (theme-state state) 'dark) "Light" "Dark"))
(defn theme-icon (state) (if (eq? (theme-state state) 'dark) "☀" "◐"))
(defn docs-navigation ()
  (el 'div (list (cls 'project-navigation))
    (el 'p (list (cls 'project-nav-label)) "Project navigation")
    (el 'nav (list (cls 'project-nav) (aria 'aria-label "Project navigation"))
      (el 'ul (list (cls 'project-nav-tree))
        (nav-link '/ "Project overview")
        (nav-link '/docs/ "Documentation overview")
        (el 'li nil
          (el 'a (list (cls 'project-nav-link) (href '/docs/foundation/) (aria 'aria-expanded "true")) "Foundation overview")
          (el 'ul (list (cls 'project-nav-children))
            (stage-link "01" '/docs/seed/ "Seed" false)
            (stage-link "02" "/docs/bootstrap/" "Bootstrap" true)
            (stage-link "03" '/docs/compiler/ "Compiler" false)
            (stage-link "04" '/docs/applications/ "Applications" false)))
        (nav-link '/docs/dom/ "05 Interfaces")
        (nav-link '/playground/ "Playground")
        (nav-link '/examples/ "Examples")))))
(defn app.initial-state () '(closed dark))
(defn app.event (state event) (if (eq? event 'toggle-menu) (list (if (eq? (menu-state state) 'open) 'closed 'open) (theme-state state)) (if (eq? event 'toggle-theme) (list (menu-state state) (if (eq? (theme-state state) 'dark) 'light 'dark)) state)))
(defn app.view (state)
  (el 'fragment (list (at 'document-theme (theme-name state)))
    (el 'a (list (cls 'skip-link) (href '#content)) "Skip to content")
    (el 'header (list (cls 'docs-header))
      (el 'a (list (cls 'brand) (href '/) (aria 'aria-label "YALisp home")) "Y" (el 'span nil "A") "LISP")
      (el 'div (list (cls 'header-actions))
        (el 'button (list (cls 'theme-toggle) (at 'type 'button) (click 'toggle-theme)) (theme-icon state) (theme-label state))
        (el 'button (list (cls 'docs-menu) (at 'type 'button) (click 'toggle-menu) (aria 'aria-label "Toggle documentation navigation") (aria 'aria-expanded (menu-aria state))) (el 'span nil) (el 'span nil))))
    (el 'div (list (cls (shell-class state)))
      (el 'aside (list (cls 'docs-nav) (aria 'aria-label "Project navigation")) (docs-navigation))
      (el 'main (list (id 'content))
        (el 'p (list (cls 'eyebrow)) "Foundation / Bootstrap")
        (el 'section nil
          (el 'p (list (cls 'section-number)) "Bootstrap")
          (el 'h1 nil "Let Lisp" (el 'br nil) (el 'em nil "grow the seed."))
          (el 'p (list (cls 'lede)) "The checked-in boot.lisp program is evaluated by the WAT seed at startup. It adds macros and reusable functions in YALISP itself, making the difference between Seed and Bootstrap directly executable.")
          (el 'p (list (cls 'interface-note)) "The real bootstrap adds cond, defn, let, boolean macros, structural equality, and list functions such as map, filter, and reduce. The separate compiler.lisp milestone loads after this bootstrap."))
        (el 'section (list (id 'source) (cls 'interface-section))
          (el 'p (list (cls 'section-number)) "01 / Checked-in source")
          (el 'h2 nil "Read what" (el 'br nil) (el 'em nil "grows the seed."))
          (el 'p nil "The source below is loaded from the same checked-in boot.lisp file that the Playground evaluates after initializing the WAT seed.")
          (el 'div (list (cls 'source-view)) (el 'div (list (cls 'source-view-header)) (el 'span nil "apps/web/public/yalisp/boot.lisp") (link "https://github.com/etdofreshai/yalisp/blob/main/apps/web/public/yalisp/boot.lisp" "GitHub ↗")) (el 'pre (list (at 'tabindex "0")) (el 'code nil documented-source))))
        (el 'section (list (id 'live-bootstrap) (cls 'interface-section))
          (el 'p (list (cls 'section-number)) "02 / Live bootstrap")
          (el 'h2 nil "Tap an example." (el 'br nil) (el 'em nil "See what Lisp adds."))
          (el 'p nil "The Playground runs each selection in a fresh WebAssembly instance that first evaluates the real Lisp bootstrap. Fibonacci is available because named recursion and defn are exercised by the implementation and regression tests.")
          (el 'p (list (cls 'interface-note)) (link "/playground/" "Open the YALISP Playground") " for the mobile-first tap-to-run gallery, optional REPL input, and real execution comparison."))
        (el 'section (list (id 'compiler-status) (cls 'interface-section))
          (el 'p (list (cls 'section-number)) "03 / Compiler status")
          (el 'h2 nil "Interpreter first." (el 'br nil) (el 'em nil "Compiler bounded."))
          (el 'p nil "YALISP loads a small Lisp-written compiler after the bootstrap. It supports exactly one parameter and nested binary integer +, -, and * expressions; every other form remains interpreted.")
          (el 'p (list (cls 'interface-note)) (link "/docs/compiler/" "Read the compiler boundary") " or use the Playground to measure the verified interpreter, JIT, and AOT paths on the same supported workload."))))))
