;;; Compiler documentation; documented-source is the exact checked-in compiler.lisp.
(define el (lambda args args))
(defn at (key value) (list key value))
(defn cls (value) (at 'class value))
(defn href (value) (at 'href value))
(defn id (value) (at 'id value))
(defn click (event) (at 'on-click event))
(defn aria (key value) (at key value))
(defn link (path label) (el 'a (list (href path)) label))
(defn nav-link (path label) (el 'li nil (el 'a (list (cls 'project-nav-link) (href path)) label)))
(defn stage-link (number path label active)
  (el 'li nil (el 'a (if active
    (list (cls "project-nav-link active") (href path) (aria 'aria-current "page"))
    (list (cls 'project-nav-link) (href path))) number " " label)))
(defn menu-state (state) (car state))
(defn theme-state (state) (car (cdr state)))
(defn shell-class (state) (if (eq? (menu-state state) 'open) "docs-shell nav-open sidebar-collapsed" 'docs-shell))
(defn menu-aria (state) (if (eq? (menu-state state) 'open) "true" "false"))
(defn theme-name (state) (if (eq? (theme-state state) 'dark) 'dark 'light))
(defn theme-label (state) (if (eq? (theme-state state) 'dark) "Light" "Dark"))
(defn theme-icon (state) (if (eq? (theme-state state) 'dark) "☀" "◐"))
(defn docs-navigation ()
  (el 'div (list (cls 'project-navigation))
    (el 'p (list (cls 'project-nav-label)) "Project navigation")
    (el 'nav (list (cls 'project-nav) (aria 'aria-label "Project navigation"))
      (el 'ul (list (cls 'project-nav-tree))
        (nav-link '/ "Project overview")
        (nav-link '/docs/ "Documentation overview")
        (el 'li nil
          (el 'a (list (cls 'project-nav-link) (href '/docs/foundation/) (aria 'aria-expanded "true")) "Foundation overview")
          (el 'ul (list (cls 'project-nav-children))
            (stage-link "01" '/docs/seed/ "Seed" false)
            (stage-link "02" '/docs/bootstrap/ "Bootstrap" false)
            (stage-link "03" "/docs/compiler/" "Compiler" true)
            (stage-link "04" '/docs/applications/ "Applications" false)))
        (nav-link '/docs/dom/ "05 Interfaces")
        (nav-link '/repl/ "REPL")
        (nav-link '/examples/ "Examples")))))
(defn flow-card (number title text)
  (el 'article nil (el 'span nil number) (el 'h2 nil title) (el 'p nil text)))
(defn grid-card (code title text)
  (el 'article nil (el 'code nil code) (el 'h3 nil title) (el 'p nil text)))
(defn app.initial-state () '(closed dark))
(defn app.event (state event)
  (if (eq? event 'toggle-menu)
    (list (if (eq? (menu-state state) 'open) 'closed 'open) (theme-state state))
    (if (eq? event 'toggle-theme)
      (list (menu-state state) (if (eq? (theme-state state) 'dark) 'light 'dark))
      state)))
(defn app.view (state)
  (el 'fragment (list (at 'document-theme (theme-name state)))
    (el 'a (list (cls 'skip-link) (href '#content)) "Skip to content")
    (el 'header (list (cls 'docs-header))
      (el 'a (list (cls 'brand) (href '/) (aria 'aria-label "YALisp home")) "Y" (el 'span nil "A") "LISP")
      (el 'div (list (cls 'header-actions))
        (el 'button (list (cls 'theme-toggle) (at 'type 'button) (click 'toggle-theme)) (theme-icon state) (theme-label state))
        (el 'button (list (cls 'docs-menu) (at 'type 'button) (click 'toggle-menu) (aria 'aria-label "Toggle documentation navigation") (aria 'aria-expanded (menu-aria state))) (el 'span nil) (el 'span nil))))
    (el 'div (list (cls (shell-class state)))
      (el 'aside (list (cls 'docs-nav) (aria 'aria-label "Project navigation") (at 'data-project-navigation 'true)) nil)
      (el 'main (list (id 'content))
        (el 'p (list (cls 'eyebrow)) "Foundation / Compiler")
        (el 'section nil
          (el 'p (list (cls 'section-number)) "Compiler")
          (el 'h1 nil "One expression." (el 'br nil) (el 'em nil "Three real paths."))
          (el 'p (list (cls 'lede)) "YALISP now has a deliberately bounded Lisp-written compiler milestone. The interpreter evaluates compiler.lisp, which lowers a verified arithmetic subset to WebAssembly text; the production build checks in the resulting AOT artifact for reproducible validation.")
          (el 'div (list (cls 'bootstrap-flow))
            (flow-card "01" "Interpreted · seed" "The WAT seed parses, evaluates, and prints every call to the benchmark function.")
            (flow-card "02" "JIT · browser" "The checked-in Lisp compiler emits a function payload, then the browser assembles, compiles, instantiates, and runs a fresh WebAssembly module.")
            (flow-card "03" "AOT · build" "The production build runs that same compiler on the same workload and checks in the resulting aot-benchmark.wasm artifact for later browser instantiation."))
          (el 'p (list (cls 'interface-note)) (link "/repl/" "Open the REPL") " to run interpreted forms directly. The compiler and its checked-in AOT artifact remain verified by the production build and regression suite."))
        (el 'section (list (id 'supported-subset) (cls 'interface-section))
          (el 'p (list (cls 'section-number)) "01 / Supported subset")
          (el 'h2 nil "Small enough" (el 'br nil) (el 'em nil "to prove."))
          (el 'div (list (cls 'reference-grid))
            (grid-card "shape" "One parameter, one expression" "The compiler accepts exactly one distinct parameter and one body form.")
            (grid-card "expressions" "Integer arithmetic" "Integer literals, the parameter, and nested binary +, -, and * forms are supported.")
            (grid-card "boundary" "Reject, never pretend" "Calls, conditionals, division, extra parameters, multiple forms, and unknown names return nil and remain interpreter-only."))
          (el 'p (list (cls 'interface-note)) "Equivalence is guaranteed only while inputs and intermediate results stay in the seed's signed 30-bit fixnum range. This milestone is not a general YALISP compiler, module system, or self-hosting compiler."))
        (el 'section (list (id 'source) (cls 'interface-section))
          (el 'p (list (cls 'section-number)) "02 / Source")
          (el 'h2 nil "Inspect the" (el 'br nil) (el 'em nil "actual compiler."))
          (el 'p nil "The compiler is adapted from Lispish's integer lowering design at commit b7214f1, while retaining YALISP's smaller current runtime boundary.")
          (el 'div (list (cls 'source-view))
            (el 'div (list (cls 'source-view-header)) (el 'span nil "apps/web/public/yalisp/compiler.lisp") (link "https://github.com/etdofreshai/yalisp/blob/main/apps/web/public/yalisp/compiler.lisp" "GitHub ↗"))
            (el 'pre (list (at 'tabindex "0")) (el 'code nil documented-source)))
          (el 'p (list (cls 'interface-note)) "AOT provenance: scripts/build-aot.mjs boots the checked-in seed, evaluates boot.lisp and this compiler.lisp, compiles the exact benchmark form, and writes the checked-in " (link "https://github.com/etdofreshai/yalisp/blob/main/apps/web/public/yalisp/aot-benchmark.wasm" "aot-benchmark.wasm") " artifact. The browser still measures fetch, WebAssembly compilation, and instantiation; this is not a general compiler or proof that unsupported forms compile."))))))
