;;; The documentation overview is a YALISP DOM application. The browser host
;;; supplies only DOM construction and click delivery; this source owns the tree.

(define el (lambda args args))
(defn at (key value) (list key value))
(defn cls (value) (at 'class value))
(defn href (value) (at 'href value))
(defn id (value) (at 'id value))
(defn click (event) (at 'on-click event))
(defn aria (key value) (at key value))
(defn link (path label) (el 'a (list (href path)) label))
(defn nav-link (path label) (el 'li nil (el 'a (list (cls 'project-nav-link) (href path)) label)))
(defn nav-anchor (number anchor label)
  (el 'li nil (el 'a (list (cls 'project-nav-link) (href (string.append "/docs/#" anchor)))
    (el 'span (list (cls 'project-nav-subindex)) number) (el 'span nil label))))
(defn card (number title copy)
  (el 'article nil (el 'code nil number) (el 'h3 nil title) (el 'p nil copy)))
(defn map-link (number path title copy)
  (el 'a (list (href path)) (el 'span nil number) (el 'strong nil title) (el 'small nil copy)))

(defn menu-state (state) (car state))
(defn theme-state (state) (car (cdr state)))
(defn shell-class (state) (if (eq? (menu-state state) 'open) "docs-shell nav-open" 'docs-shell))
(defn menu-aria (state) (if (eq? (menu-state state) 'open) "true" "false"))
(defn theme-name (state) (if (eq? (theme-state state) 'dark) 'dark 'light))
(defn theme-label (state) (if (eq? (theme-state state) 'dark) "Light" "Dark"))
(defn theme-icon (state) (if (eq? (theme-state state) 'dark) "☀" "◐"))

(defn docs-overview-nav-item ()
  (el 'li nil
    (el 'a (list (cls 'project-nav-link) (href "/docs/") (aria 'aria-current "page")) "Documentation overview")
    (el 'ul (list (cls 'project-nav-children))
      (nav-anchor "01" "introduction" "Introduction")
      (nav-anchor "02" "getting-started" "Getting started")
      (nav-anchor "03" "language" "Language guide")
      (nav-anchor "04" "core-repl" "REPL that grows into a compiler")
      (nav-anchor "05" "foundation" "Foundation")
      (nav-anchor "06" "reference-interfaces" "Interfaces")
      (nav-anchor "07" "game-runtime" "Game Runtime")
      (nav-anchor "08" "examples" "Examples"))))

(defn foundation-nav-item ()
  (el 'li nil
    (el 'a (list (cls 'project-nav-link) (href "/docs/foundation/") (aria 'aria-expanded "false")) "Foundation overview")
    (el 'ul (list (cls 'project-nav-children) (at 'hidden 'hidden))
      (nav-link '/docs/seed/ "01 Seed")
      (nav-link '/docs/bootstrap/ "02 Bootstrap")
      (nav-link '/docs/compiler/ "03 Compiler")
      (nav-link '/docs/applications/ "04 Applications"))))

(defn interfaces-nav-item ()
  (el 'li nil
    (el 'a (list (cls 'project-nav-link) (href '/docs/#reference-interfaces) (aria 'aria-expanded "false")) "05 Interfaces")
    (el 'ul (list (cls 'project-nav-children) (at 'hidden 'hidden))
      (nav-link '/docs/assembly/ "05.01 Assembly")
      (nav-link '/docs/system-interface/ "05.02 System interface")
      (nav-link '/docs/dom/ "05.03 DOM")
      (nav-link '/docs/sdl/ "05.04 SDL"))))

(defn docs-navigation ()
  (el 'div (list (cls 'project-navigation))
    (el 'p (list (cls 'project-nav-label)) "Project navigation")
    (el 'nav (list (cls 'project-nav) (aria 'aria-label "Project navigation"))
      (el 'ul (list (cls 'project-nav-tree))
        (nav-link '/ "Project overview")
        (docs-overview-nav-item)
        (foundation-nav-item)
        (interfaces-nav-item)
        (nav-link '/playground/ "Playground")
        (nav-link '/examples/ "Examples")))))

(defn language-examples ()
  (el 'div (list (cls 'language-examples))
    (el 'article (list (cls 'language-example))
      (el 'p (list (cls 'example-label)) "01 / Arithmetic")
      (el 'h3 nil "Calls use prefix notation")
      (el 'pre nil (el 'code nil "(* 6 7)  ; => 42\n(- 6 1)  ; => 5"))
      (el 'p nil "The executable seed supports these prefix integer operations. The Playground evaluates the same call shape through WebAssembly rather than displaying a precomputed result."))
    (el 'article (list (cls 'language-example))
      (el 'p (list (cls 'example-label)) "02 / Functions")
      (el 'h3 nil "Bind a lambda with define")
      (el 'pre nil (el 'code nil "(define factorial\n  (lambda (n)\n    (if (<= n 1) 1 (* n (factorial (- n 1))))))\n\n(factorial 6)  ; => 720"))
      (el 'p nil "This exact example uses forms implemented by the executable seed: a named recursive function, one parameter, a conditional, and ordinary prefix calls."))
    (el 'article (list (cls 'language-example))
      (el 'p (list (cls 'example-label)) "03 / Organization")
      (el 'h3 nil "Module syntax is not implemented")
      (el 'p nil "No YALisp module form, import form, loader, or module test exists in the current repository. Modules remain a future language milestone."))
    (el 'article (list (cls 'language-example))
      (el 'p (list (cls 'example-label)) "04 / Self-description")
      (el 'h3 nil "Ask the Lisp compiler for a function payload")
      (el 'pre nil (el 'code nil "(cc.compile '(x) '((+ (* x x) 1)))\n; => (param i32) (result i32) ..."))
      (el 'p nil "This cc.compile form is executed by the current seed after loading boot.lisp and compiler.lisp. The compiler is intentionally limited to one-parameter integer expressions."))))

(defn app.initial-state () '(closed dark))

(defn app.event (state event)
  (if (eq? event 'toggle-menu)
      (list (if (eq? (menu-state state) 'open) 'closed 'open) (theme-state state))
      (if (eq? event 'toggle-theme)
          (list (menu-state state) (if (eq? (theme-state state) 'dark) 'light 'dark))
          state)))

(defn app.view (state)
  (el 'fragment (list (at 'document-theme (theme-name state)))
    (el 'a (list (cls 'skip-link) (href '#content)) "Skip to content")
    (el 'header (list (cls 'docs-header))
      (el 'a (list (cls 'brand) (href '/) (aria 'aria-label "YALisp home")) "Y" (el 'span nil "A") "LISP")
      (el 'div (list (cls 'header-actions))
        (el 'button (list (cls 'theme-toggle) (at 'type 'button) (click 'toggle-theme)) (theme-icon state) (theme-label state))
        (el 'button (list (cls 'docs-menu) (at 'type 'button) (click 'toggle-menu) (aria 'aria-label "Toggle documentation navigation") (aria 'aria-expanded (menu-aria state))) (el 'span nil) (el 'span nil))))
    (el 'div (list (cls (shell-class state)))
      (el 'aside (list (cls 'docs-nav) (aria 'aria-label "Project navigation")) (docs-navigation))
      (el 'main (list (id 'content))
        (el 'p (list (cls 'eyebrow)) "YALisp documentation")
        (el 'section (list (id 'introduction))
          (el 'p (list (cls 'section-number)) "01")
          (el 'h1 nil "Start small." (el 'br nil) (el 'em nil "Understand everything."))
          (el 'p (list (cls 'lede)) "A small Lisp with portable interfaces for computation, systems work, and interactive applications."))
        (el 'section (list (id 'getting-started))
          (el 'p (list (cls 'section-number)) "02")
          (el 'h2 nil "Getting started")
          (el 'p nil "Set up a workspace, run your first expression, and get comfortable with the shape of the language."))
        (el 'section (list (id 'language))
          (el 'p (list (cls 'section-number)) "03")
          (el 'h2 nil "Language guide")
          (el 'p nil "Expressions, functions, and the core ideas that keep the language small, readable, and capable of describing its own implementation.")
          (el 'p (list (cls 'interface-note)) "Implementation status: this repository ships a runnable WAT reader and evaluator, a Lisp-written bootstrap, and a bounded Lisp-written arithmetic compiler exercised in the Playground. Modules and a general compiler remain future work.")
          (language-examples))
        (el 'section (list (id 'core-repl))
          (el 'p (list (cls 'section-number)) "04")
          (el 'h2 nil "A REPL that grows into a compiler")
          (el 'p nil "The Playground starts with a WAT interpreter extended by boot.lisp. For its bounded compiler benchmark it then evaluates compiler.lisp, proving the first Lisp-written lowering stage on top of that same base.")
          (el 'div (list (cls 'reference-grid))
            (card "read" "Accept a Lisp form" "The REPL receives a form and keeps the language syntax close to the implementation that understands it.")
            (card "compile" "Turn a form into executable work" "The bootstrap compiler lowers the supported form into WebAssembly-oriented instructions.")
            (card "evaluate" "Return a result and continue" "The current environment reports its value or error and remains ready for the next expression.")))
        (el 'section (list (id 'foundation) (cls 'interface-section))
          (el 'p (list (cls 'section-number)) "05")
          (el 'h2 nil "Foundation")
          (el 'p nil "YALisp grows from a small executable seed into a real Lisp bootstrap, a bounded compiler, and practical applications.")
          (el 'div (list (cls 'interface-map) (aria 'aria-label "YALisp foundation documentation"))
            (map-link "—" "/docs/foundation/" "Foundation" "The complete bootstrapping path")
            (map-link "01" "/docs/seed/" "Seed" "The minimal trusted runtime")
            (map-link "02" "/docs/bootstrap/" "Bootstrap" "Growing the language from Lisp")
            (map-link "03" "/docs/compiler/" "Compiler" "Verified bounded JIT and ahead-of-time milestone")
            (map-link "04" "/docs/applications/" "Applications" "Using the language in real tools"))
          (el 'p (list (cls 'interface-note)) (link "/playground/" "Open the YALISP Playground") " to run the executable Seed and Lisp Bootstrap directly."))
        (el 'section (list (id 'reference-interfaces))
          (el 'p (list (cls 'section-number)) "06")
          (el 'h2 nil "Interfaces")
          (el 'p nil "YALisp interface contracts have narrow jobs, so a program can be direct when it needs to be and portable when it can be.")
          (el 'div (list (cls 'interface-map) (aria 'aria-label "The four YALisp interfaces"))
            (map-link "01" "/docs/assembly/" "Assembly" "WebAssembly primitives")
            (map-link "02" "/docs/system-interface/" "System interface" "Portable system services")
            (map-link "03" "/docs/dom/" "DOM" "Portable documents and events")
            (map-link "04" "/docs/sdl/" "SDL" "Concrete multimedia runtime")))
        (el 'section (list (id 'game-runtime) (cls 'interface-section))
          (el 'p (list (cls 'section-number)) "07")
          (el 'h2 nil "Game runtime")
          (el 'p nil "This intended architecture describes game-facing runtime services above the existing interfaces. Its callable APIs are not implemented yet.")
          (el 'div (list (cls 'reference-grid))
            (card "simulation update" "Stable world steps" "Gameplay and physics advance on a distinct fixed cadence.")
            (card "render update" "Independently paced frames" "Presentation samples the latest simulation state on its own cadence.")
            (card "time" "Clocks and time scale" "Runtime time separates elapsed real time, simulation time, frame deltas, and controlled time scale.")
            (card "input and events" "Intent enters the simulation" "DOM or SDL events are normalized and consumed at defined update boundaries.")
            (card "graphics and assets" "Sprites, sheets, and resources" "Game-facing primitives cover sprites, sheets, loading, ownership, reuse, and release.")
            (card "networking" "Synchronize with simulation" "Future networking exchanges simulation inputs or state on simulation boundaries.")))
        (el 'section (list (id 'examples))
          (el 'p (list (cls 'section-number)) "08")
          (el 'h2 nil "Examples")
          (el 'p nil "Short programs to explore, change, and use as a starting point for your own experiments.")
          (el 'div (list (cls 'interface-map) (aria 'aria-label "YALisp examples"))
            (map-link "01" "/examples/hello-world/" "CLI Hello World" "Complete seed form, browser host, and command-line host")
            (map-link "02" "/examples/pong/" "Pong" "Complete YALISP app through a generic Canvas launcher")
            (map-link "03" "/examples/breakout/" "Breakout" "Complete YALISP app through a generic Canvas launcher")
            (map-link "04" "/examples/asteroids/" "Asteroids" "Complete YALISP app through a generic Canvas launcher"))
          (el 'p (list (cls 'interface-note)) "The games do not claim an implemented native YALISP graphics runtime. Their complete YALISP application logic currently runs through a generic browser Canvas binding.")))))))
