;;; Foundation is rendered by the generic YALISP DOM application bridge.

(define el (lambda args args))
(defn at (key value) (list key value))
(defn cls (value) (at 'class value))
(defn href (value) (at 'href value))
(defn id (value) (at 'id value))
(defn click (event) (at 'on-click event))
(defn aria (key value) (at key value))
(defn nav-link (path label) (el 'li nil (el 'a (list (cls 'project-nav-link) (href path)) label)))
(defn stage-link (number path label) (el 'li nil (el 'a (list (cls 'project-nav-link) (href path)) number " " label)))
(defn menu-state (state) (car state))
(defn theme-state (state) (car (cdr state)))
(defn shell-class (state) (if (eq? (menu-state state) 'open) "docs-shell nav-open sidebar-collapsed" 'docs-shell))
(defn menu-aria (state) (if (eq? (menu-state state) 'open) "true" "false"))
(defn theme-name (state) (if (eq? (theme-state state) 'dark) 'dark 'light))
(defn theme-label (state) (if (eq? (theme-state state) 'dark) "Light" "Dark"))
(defn theme-icon (state) (if (eq? (theme-state state) 'dark) "☀" "◐"))
(defn stage (number title copy)
  (el 'article nil (el 'span nil number) (el 'h2 nil title) (el 'p nil copy)))

(defn foundation-navigation ()
  (el 'div (list (cls 'project-navigation))
    (el 'p (list (cls 'project-nav-label)) "Project navigation")
    (el 'nav (list (cls 'project-nav) (aria 'aria-label "Project navigation"))
      (el 'ul (list (cls 'project-nav-tree))
        (nav-link '/ "Project overview")
        (nav-link '/docs/ "Documentation overview")
        (el 'li nil
          (el 'a (list (cls 'project-nav-link) (href "/docs/foundation/") (aria 'aria-current "page") (aria 'aria-expanded "true")) "Foundation overview")
          (el 'ul (list (cls 'project-nav-children))
            (stage-link "01" '/docs/seed/ "Seed")
            (stage-link "02" '/docs/bootstrap/ "Bootstrap")
            (stage-link "03" '/docs/compiler/ "Compiler")
            (stage-link "04" '/docs/applications/ "Applications")))
        (el 'li nil
          (el 'a (list (cls 'project-nav-link) (href '/docs/#reference-interfaces) (aria 'aria-expanded "false")) "05 Interfaces")
          (el 'ul (list (cls 'project-nav-children) (at 'hidden 'hidden))
            (stage-link "05.01" '/docs/assembly/ "Assembly")
            (stage-link "05.02" '/docs/system-interface/ "System interface")
            (stage-link "05.03" '/docs/dom/ "DOM")
            (stage-link "05.04" '/docs/sdl/ "SDL")))
        (nav-link '/repl/ "REPL")
        (nav-link '/examples/ "Examples")))))

(defn app.initial-state () '(closed dark))
(defn app.event (state event)
  (if (eq? event 'toggle-menu)
      (list (if (eq? (menu-state state) 'open) 'closed 'open) (theme-state state))
      (if (eq? event 'toggle-theme)
          (list (menu-state state) (if (eq? (theme-state state) 'dark) 'light 'dark))
          state)))

(defn app.view (state)
  (el 'fragment (list (at 'document-theme (theme-name state)))
    (el 'a (list (cls 'skip-link) (href '#content)) "Skip to content")
    (el 'header (list (cls 'docs-header))
      (el 'a (list (cls 'brand) (href '/) (aria 'aria-label "YALisp home")) "Y" (el 'span nil "A") "LISP")
      (el 'div (list (cls 'header-actions))
        (el 'button (list (cls 'theme-toggle) (at 'type 'button) (click 'toggle-theme)) (theme-icon state) (theme-label state))
        (el 'button (list (cls 'docs-menu) (at 'type 'button) (click 'toggle-menu) (aria 'aria-label "Toggle documentation navigation") (aria 'aria-expanded (menu-aria state))) (el 'span nil) (el 'span nil))))
    (el 'div (list (cls (shell-class state)))
      (el 'aside (list (cls 'docs-nav) (aria 'aria-label "Project navigation") (at 'data-project-navigation 'true)) nil)
      (el 'main (list (id 'content))
        (el 'p (list (cls 'eyebrow)) "YALisp architecture")
        (el 'section (list (id 'foundation))
          (el 'p (list (cls 'section-number)) "Foundation")
          (el 'h1 nil "Grow the language" (el 'br nil) (el 'em nil "from a small seed."))
          (el 'p (list (cls 'lede)) "YALisp begins with the smallest WebAssembly-backed seed that can read and run enough Lisp to construct the next layer. Each stage builds the tools that make the following stage possible.")
          (el 'div (list (cls 'bootstrap-flow) (aria 'aria-label "The YALisp bootstrapping sequence"))
            (stage "01" "Seed" "A minimal WebAssembly foundation supplies the primitive values, memory, control flow, and reader support required to begin.")
            (stage "02" "Bootstrap" "That seed runs a small Lisp environment with enough forms and functions to define the language in the language.")
            (stage "03" "Compiler" "The bootstrap is used to create the YALisp compiler: it reads YALisp forms, lowers them through the foundation, and produces runnable output.")
            (stage "04" "Applications" "With the compiler available, YALisp can build applications against Assembly, System Interface, and DOM without requiring a large separate runtime."))
          (el 'p (list (cls 'interface-note)) "The purpose is not to hide the implementation. The seed stays deliberately small and inspectable; the bootstrap and compiler are YALisp code that can grow with the language."))))))
