;;; YALISP's landing document. The browser launches this source through the
;;; generic DOM bridge; its structure, links, text, and menu state are Lisp.

(define el (lambda args args))
(defn at (key value) (list key value))
(defn cls (value) (at 'class value))
(defn href (value) (at 'href value))
(defn id (value) (at 'id value))
(defn click (event) (at 'on-click event))
(defn aria (key value) (at key value))
(defn link (path label) (el 'a (list (href path)) label))
(defn nav-link (path label) (el 'li nil (link path label)))

(define factorial
  (lambda (n)
    (if (<= n 1) 1 (* n (factorial (- n 1))))))

;; The landing example is executable documentation, not a display-only claim.
(define landing-factorial-example (factorial 6))

(defn menu-state (state) (car state))
(defn theme-state (state) (car (cdr state)))
(defn menu-class (state) (if (eq? (menu-state state) 'open) "site-header menu-open" 'site-header))
(defn menu-aria (state) (if (eq? (menu-state state) 'open) "true" "false"))
(defn theme-label (state) (if (eq? (theme-state state) 'dark) "Light" "Dark"))
(defn theme-icon (state) (if (eq? (theme-state state) 'dark) "☀" "◐"))
(defn theme-name (state) (if (eq? (theme-state state) 'dark) 'dark 'light))

(defn features ()
  (el 'div (list (cls 'feature-list))
    (el 'article (list (cls 'feature-card)) (el 'span nil "01") (el 'h3 nil "Small enough to hold") (el 'p nil "A seed you can inspect, run, and grow without losing the thread."))
    (el 'article (list (cls 'feature-card)) (el 'span nil "02") (el 'h3 nil "Portable by design") (el 'p nil "Interfaces make the same program at home in the browser or on a native host."))
    (el 'article (list (cls 'feature-card)) (el 'span nil "03") (el 'h3 nil "Built in the open") (el 'p nil "The executable seed, bootstrap library, and compiler source are part of the documentation."))))

(defn app.initial-state () '(closed dark))

(defn app.event (state event)
  (if (eq? event 'toggle-menu)
      (list (if (eq? (menu-state state) 'open) 'closed 'open) (theme-state state))
      (if (eq? event 'toggle-theme)
          (list (menu-state state) (if (eq? (theme-state state) 'dark) 'light 'dark))
          state)))

(defn app.view (state)
  (el 'fragment (list (at 'document-theme (theme-name state)))
    (el 'header (list (cls (menu-class state)))
      (el 'a (list (cls 'brand) (href '/) (aria 'aria-label "YALisp home")) (el 'span nil "Y") (el 'span (list (cls 'brand-accent)) "A") (el 'span nil "LISP"))
      (el 'div (list (cls 'header-controls))
        (el 'button (list (cls 'theme-toggle) (at 'type 'button) (click 'toggle-theme)) (theme-icon state) "·" (theme-label state))
        (el 'button (list (cls 'menu-button) (at 'type 'button) (click 'toggle-menu) (aria 'aria-label "Toggle project navigation") (aria 'aria-expanded (menu-aria state))) (el 'span nil) (el 'span nil))))
    (el 'aside (list (cls 'site-nav-drawer) (aria 'aria-label "Project navigation") (at 'data-project-navigation 'true)) nil)
    (el 'main (list (id 'main))
      (el 'section (list (cls 'hero) (id 'top))
        (el 'div (list (cls 'hero-eyebrow)) (el 'span (list (cls 'eyebrow-mark)) "λ") (el 'span nil "A little Lisp with a lot to teach"))
        (el 'h1 nil "Make the machine" (el 'br nil) "feel " (el 'em nil "small") " again.")
        (el 'div (list (cls 'hero-footer))
          (el 'p nil "YALisp is a compact, readable Lisp for curious programmers who want to understand the whole thing.")
          (el 'a (list (cls 'circle-link) (href '#why) (aria 'aria-label "Discover YALisp")) "↓")))
      (el 'section (list (cls 'manifesto) (id 'why))
        (el 'p (list (cls 'section-kicker)) "Why another Lisp?")
        (el 'div (list (cls 'manifesto-grid))
          (el 'h2 nil "Because understanding" (el 'br nil) "is a feature.")
          (el 'div (list (cls 'manifesto-copy))
            (el 'p nil "Modern software can feel like a stack of black boxes. YALisp goes the other direction: a language small enough to explore and useful enough to make the exploration worthwhile.")
            (el 'a (list (cls 'text-link) (href '#language)) "See it in motion →")))
        (features))
      (el 'section (list (cls 'language) (id 'language))
        (el 'p (list (cls "section-kicker section-kicker-light")) "The language")
        (el 'h2 nil "Familiar shape." (el 'br nil) (el 'em nil "Fresh perspective."))
        (el 'p nil "Expressions are data. Functions are values. The syntax stays out of the way so the ideas can stay in view.")
        (el 'pre (list (cls 'code-window)) "factorial example evaluates six to 720"))
      (el 'section (list (cls 'closing))
        (el 'p (list (cls "section-kicker section-kicker-light")) "Come build with us")
        (el 'h2 nil "Curiosity looks" (el 'br nil) "good on you.")
        (el 'a (list (cls 'button) (href 'https://github.com/ETdoFreshAI/yalisp)) "Explore on GitHub ↗")))
    (el 'footer nil (el 'p nil "Small language. Big ideas.") (el 'p nil "Built with YALISP."))))
