;;; YALISP's landing document. The browser launches this source through the
;;; generic DOM bridge; its structure, links, text, and menu state are Lisp.

(define el (lambda args args))
(defn at (key value) (list key value))
(defn cls (value) (at 'class value))
(defn href (value) (at 'href value))
(defn id (value) (at 'id value))
(defn click (event) (at 'on-click event))
(defn aria (key value) (at key value))
(defn link (path label) (el 'a (list (href path)) label))
(defn nav-link (path label) (el 'li nil (link path label)))

(define factorial
  (lambda (n)
    (if (<= n 1) 1 (* n (factorial (- n 1))))))

(defn menu-state (state) (car state))
(defn theme-state (state) (car (cdr state)))
(defn menu-class (state) (if (eq? (menu-state state) 'open) 'site-header~menu-open 'site-header))
(defn menu-aria (state) (if (eq? (menu-state state) 'open) 'true 'false))
(defn theme-label (state) (if (eq? (theme-state state) 'dark) 'Light 'Dark))
(defn theme-icon (state) (if (eq? (theme-state state) 'dark) '☀ '◐))
(defn theme-name (state) (if (eq? (theme-state state) 'dark) 'dark 'light))

(defn site-nav ()
  (el 'nav (list (cls 'project-nav) (aria 'aria-label 'Project~navigation))
    (el 'ul (list (cls 'project-nav-tree))
      (nav-link '/ 'Project~overview)
      (nav-link '/docs/ 'Documentation~overview)
      (nav-link '/docs/foundation/ 'Foundation~overview)
      (nav-link '/docs/seed/ '01~Seed)
      (nav-link '/docs/bootstrap/ '02~Bootstrap)
      (nav-link '/docs/compiler/ '03~Compiler)
      (nav-link '/docs/applications/ '04~Applications)
      (nav-link '/docs/dom/ '05~Interfaces)
      (nav-link '/playground/ 'Playground)
      (nav-link '/examples/ 'Examples))))

(defn features ()
  (el 'div (list (cls 'feature-list))
    (el 'article (list (cls 'feature-card)) (el 'span nil '01) (el 'h3 nil 'Small~enough~to~hold) (el 'p nil 'A~seed~you~can~inspect~run~and~grow~without~losing~the~thread.))
    (el 'article (list (cls 'feature-card)) (el 'span nil '02) (el 'h3 nil 'Portable~by~design) (el 'p nil 'Interfaces~make~the~same~program~at~home~in~the~browser~or~on~a~native~host.))
    (el 'article (list (cls 'feature-card)) (el 'span nil '03) (el 'h3 nil 'Built~in~the~open) (el 'p nil 'The~executable~seed~bootstrap~library~and~compiler~source~are~part~of~the~documentation.))))

(defn app.initial-state () '(closed dark))

(defn app.event (state event)
  (if (eq? event 'toggle-menu)
      (list (if (eq? (menu-state state) 'open) 'closed 'open) (theme-state state))
      (if (eq? event 'toggle-theme)
          (list (menu-state state) (if (eq? (theme-state state) 'dark) 'light 'dark))
          state)))

(defn app.view (state)
  (el 'fragment (list (at 'document-theme (theme-name state)))
    (el 'header (list (cls (menu-class state)))
      (el 'a (list (cls 'brand) (href '/) (aria 'aria-label 'YALisp~home)) (el 'span nil 'Y) (el 'span (list (cls 'brand-accent)) 'A) (el 'span nil 'LISP))
      (el 'div (list (cls 'rail-intro)) (el 'p nil 'Project~index) (el 'strong nil 'One~small~language~from~seed~to~applications.))
      (el 'div (list (cls 'landing-project-navigation)) (site-nav))
      (el 'div (list (cls 'header-controls))
        (el 'button (list (cls 'theme-toggle) (at 'type 'button) (click 'toggle-theme)) (theme-icon state) '· (theme-label state))
        (el 'button (list (cls 'menu-button) (at 'type 'button) (click 'toggle-menu) (aria 'aria-expanded (menu-aria state))) 'Menu)))
    (el 'main (list (id 'main))
      (el 'section (list (cls 'hero) (id 'top))
        (el 'p (list (cls 'hero-eyebrow)) 'λ~A~little~Lisp~with~a~lot~to~teach)
        (el 'h1 nil 'Make~the~machine~feel~small~again.)
        (el 'div (list (cls 'hero-footer))
          (el 'p nil 'YALisp~is~a~compact~readable~Lisp~for~curious~programmers~who~want~to~understand~the~whole~thing.)
          (link '#why 'Discover~YALisp~→)))
      (el 'section (list (cls 'manifesto) (id 'why))
        (el 'p (list (cls 'section-kicker)) 'Why~another~Lisp?)
        (el 'h2 nil 'Because~understanding~is~a~feature.)
        (el 'p nil 'Modern~software~can~feel~like~a~stack~of~black~boxes.~YALisp~goes~the~other~direction:~a~language~small~enough~to~explore~and~useful~enough~to~make~the~exploration~worthwhile.)
        (features))
      (el 'section (list (cls 'language) (id 'language))
        (el 'p (list (cls 'section-kicker~section-kicker-light)) 'The~language)
        (el 'h2 nil 'Familiar~shape.~Fresh~perspective.)
        (el 'p nil 'Expressions~are~data.~Functions~are~values.~The~syntax~stays~out~of~the~way~so~the~ideas~can~stay~in~view.)
        (el 'pre (list (cls 'code-window)) 'factorial~example~evaluates~six~to~720))
      (el 'section (list (cls 'closing))
        (el 'p (list (cls 'section-kicker~section-kicker-light)) 'Come~build~with~us)
        (el 'h2 nil 'Curiosity~looks~good~on~you.)
        (link 'https://github.com/ETdoFreshAI/yalisp 'Explore~on~GitHub~↗)))
    (el 'footer nil (el 'p nil 'Small~language.~Big~ideas.) (el 'p nil 'Built~with~YALISP.))))
