;;; The WAT text arrives as the checked-in documented-source binding. All page
;;; structure, source presentation, and interaction state remain YALISP.

(define el (lambda args args))
(defn at (key value) (list key value))
(defn cls (value) (at 'class value))
(defn href (value) (at 'href value))
(defn id (value) (at 'id value))
(defn click (event) (at 'on-click event))
(defn aria (key value) (at key value))
(defn link (path label) (el 'a (list (href path)) label))
(defn nav-link (path label) (el 'li nil (el 'a (list (cls 'project-nav-link) (href path)) label)))
(defn stage-link (number path label current)
  (el 'li nil (el 'a (list (cls (if current "project-nav-link active" 'project-nav-link)) (href path) (if current (aria 'aria-current "page") (at 'data-nav 'stage))) number " " label)))
(defn card (name title copy) (el 'article nil (el 'code nil name) (el 'h3 nil title) (el 'p nil copy)))
(defn menu-state (state) (car state))
(defn theme-state (state) (car (cdr state)))
(defn shell-class (state) (if (eq? (menu-state state) 'open) "docs-shell nav-open sidebar-collapsed" 'docs-shell))
(defn menu-aria (state) (if (eq? (menu-state state) 'open) "true" "false"))
(defn theme-name (state) (if (eq? (theme-state state) 'dark) 'dark 'light))
(defn theme-label (state) (if (eq? (theme-state state) 'dark) "Light" "Dark"))
(defn theme-icon (state) (if (eq? (theme-state state) 'dark) "☀" "◐"))

(defn seed-navigation ()
  (el 'div (list (cls 'project-navigation))
    (el 'p (list (cls 'project-nav-label)) "Project navigation")
    (el 'nav (list (cls 'project-nav) (aria 'aria-label "Project navigation"))
      (el 'ul (list (cls 'project-nav-tree))
        (nav-link '/ "Project overview")
        (nav-link '/docs/ "Documentation overview")
        (el 'li nil
          (el 'a (list (cls 'project-nav-link) (href '/docs/foundation/) (aria 'aria-expanded "true")) "Foundation overview")
          (el 'ul (list (cls 'project-nav-children))
            (stage-link "01" "/docs/seed/" "Seed" true)
            (stage-link "02" '/docs/bootstrap/ "Bootstrap" false)
            (stage-link "03" '/docs/compiler/ "Compiler" false)
            (stage-link "04" '/docs/applications/ "Applications" false)))
        (el 'li nil
          (el 'a (list (cls 'project-nav-link) (href '/docs/#reference-interfaces) (aria 'aria-expanded "false")) "05 Interfaces")
          (el 'ul (list (cls 'project-nav-children) (at 'hidden 'hidden))
            (nav-link '/docs/assembly/ "05.01 Assembly")
            (nav-link '/docs/system-interface/ "05.02 System interface")
            (nav-link '/docs/dom/ "05.03 DOM")
            (nav-link '/docs/sdl/ "05.04 SDL")))
        (nav-link '/repl/ "REPL")
        (nav-link '/examples/ "Examples")))))

(defn app.initial-state () '(closed dark))
(defn app.event (state event)
  (if (eq? event 'toggle-menu)
      (list (if (eq? (menu-state state) 'open) 'closed 'open) (theme-state state))
      (if (eq? event 'toggle-theme) (list (menu-state state) (if (eq? (theme-state state) 'dark) 'light 'dark)) state)))

(defn app.view (state)
  (el 'fragment (list (at 'document-theme (theme-name state)))
    (el 'a (list (cls 'skip-link) (href '#content)) "Skip to content")
    (el 'header (list (cls 'docs-header))
      (el 'a (list (cls 'brand) (href '/) (aria 'aria-label "YALisp home")) "Y" (el 'span nil "A") "LISP")
      (el 'div (list (cls 'header-actions))
        (el 'button (list (cls 'theme-toggle) (at 'type 'button) (click 'toggle-theme)) (theme-icon state) (theme-label state))
        (el 'button (list (cls 'docs-menu) (at 'type 'button) (click 'toggle-menu) (aria 'aria-label "Toggle documentation navigation") (aria 'aria-expanded (menu-aria state))) (el 'span nil) (el 'span nil))))
    (el 'div (list (cls (shell-class state)))
      (el 'aside (list (cls 'docs-nav) (aria 'aria-label "Project navigation") (at 'data-project-navigation 'true)) nil)
      (el 'main (list (id 'content))
        (el 'p (list (cls 'eyebrow)) "Foundation / Seed")
        (el 'section nil
          (el 'p (list (cls 'section-number)) "Seed")
          (el 'h1 nil "The smallest" (el 'br nil) (el 'em nil "executable core."))
          (el 'p (list (cls 'lede)) "The YALISP seed is a real WebAssembly interpreter assembled from checked-in WAT. It reads S-expressions, evaluates a deliberately small language, and prints actual results in the browser.")
          (el 'p (list (cls 'interface-note)) "This implementation is derived from the verified M9 seed in Lispish commit c78a2be. YALISP keeps one host.write import, a bounded eight-page memory, and no simulated results."))
        (el 'section (list (id 'supported-surface) (cls 'interface-section))
          (el 'p (list (cls 'section-number)) "01 / Supported surface")
          (el 'h2 nil "Enough Lisp" (el 'br nil) (el 'em nil "to grow Lisp."))
          (el 'div (list (cls 'reference-grid))
            (card "values" "Small tagged model" "Integers, booleans, nil, symbols, strings, pairs, closures, macros, and primitives live in WebAssembly memory.")
            (card "forms" "Seven evaluator forms" "quote, if, lambda, macro, define, set!, and begin are implemented by the seed.")
            (card "primitives" "Lists, numbers, and strings" "Cons cells, arithmetic, comparisons, type predicates, and a small string surface are available before bootstrap."))
          (el 'p (list (cls 'interface-note)) "The seed does not provide garbage collection, recoverable errors, modules, system or DOM access, or general compilation. Each gallery run starts a fresh bounded instance."))
        (el 'section (list (id 'source) (cls 'interface-section))
          (el 'p (list (cls 'section-number)) "02 / Checked-in source")
          (el 'h2 nil "Read the" (el 'br nil) (el 'em nil "actual kernel."))
          (el 'p nil "The WAT below is the same checked-in bootstrap.wat file that the build assembles into seed.wasm.")
          (el 'div (list (cls 'source-view))
            (el 'div (list (cls 'source-view-header)) (el 'span nil "apps/web/src/seed/bootstrap.wat") (link "https://github.com/etdofreshai/yalisp/blob/main/apps/web/src/seed/bootstrap.wat" "GitHub ↗"))
            (el 'pre (list (at 'tabindex "0")) (el 'code nil documented-source))))
        (el 'section (list (id 'live-seed) (cls 'interface-section))
          (el 'p (list (cls 'section-number)) "03 / Live seed")
          (el 'h2 nil "Tap a form." (el 'br nil) (el 'em nil "Run the real evaluator."))
          (el 'p nil "The REPL lets you switch between Seed and Bootstrap while keeping a bounded live session for each stage.")
          (el 'p (list (cls 'interface-note)) (link "/repl/" "Open the YALISP REPL") " to load Seed and Bootstrap examples, edit them, and run the real interpreter."))))))
